### PR TITLE
Use common prefix for all options

### PR DESCRIPTION
**Pull request by MarcelCoding**
## Summary by CodeRabbit

- **New Features**
	- Updated the configuration variable for smart editing from `g:suda_smart_edit` to `g:suda#smart_edit` for improved clarity.
	- Enhanced logic for the smart edit feature to accommodate the new variable.
	- Added commands for reading and writing files using the `suda://` protocol.

- **Documentation**
	- Updated documentation for the *suda* plugin to reflect the new naming convention and improve clarity.

### CODE REVIEW

**Comment by lambdalisue** [comment]
Unfortunately, `g:suda_xxxxx` and `g:suda#xxxxx` are entirely different in Vim, making this change unacceptable.

**Comment by MarcelCoding** [comment]
How different? Could you send me a link to the relevant part of the documentation?

**Comment by lambdalisue** [comment]
Well, `g:suda#xxxxx` automatically load `autoload/suda.vim` but `g:suda_xxxxx`. See `:help autoload`

**Comment by MarcelCoding** [comment]
It is not desired that suda_xxx also automatically loads suda?

**Comment by lambdalisue** [comment]
No. `g:suda_smart_edit` is used in `plugin/suda.vim` and it doesn't need to load `autoload/suda.vim`

**Pull request closed without merging**
